### ISSUE TITLE
MAL mark some anime series completed  when play on stremio episodes already marked as watched on MAL 

### ISSUE THREAD

**Issue by Phoenomenal** [SageTendo/mal-stremio-addon#18]
Hi,  found a bug that affects at least some anime series (One Piece and Detective Conan affected for me.  Other series a watch now wont affected) .     For example if on MAL  episodes 1-10 marked as watched already and i play episodes 1-9 on Stremio than MAL change watched anime episodes on these series  to the episode a just play  and also mark series as completed. Same if a watch episode 10 excluding the episode count don't change since 10 already was marked on MAL but still marks  series  as completed.  The right behaviour is when you watch already marked episodes that it shouldn't do nothing on MAL.   

Can you please look at this and fix if possible?

Also a quick question:  Am i understanding correctly that mal-stremio addon uses and only works for  Kitsu catalog (tried both cinemeta and TMDB but nothing was marked on MAL) ?     Is it possible to add TMDB catalogue to be also be tracked ?

**Comment by SageTendo** [comment]
Thanks for letting me know about the problem.
So if I understand correctly, it's changing "watched" to "watching"? 

I'm currently busy with my final year project, but I'll take a look at it once I get time.

**Comment by Phoenomenal** [comment]
Thanks for quick reply!  Sorry, english  not my primarly language.  Its vise versa if i watch series which have on MAL status "watching"  (One Piece and Detective conan affected by it) and play on stremio older episodes  which already marked on MAL eps seen as watched then   status on MAL changed to "completed"  and episode count on MAL also changes to this episode you just played.  When have time you  test One Piece :  mark it on MAL as watching and  chose some episodes count like if already seen lets say 10 episodes.  Than just play episode 9 on stremio and you will trigger this bug.   And strange that only some anime affected by this bug while others wont....

**Comment by SageTendo** [comment]
No need to be sorry about that about that :)
I took a look at the bug by watching One Piece, and found what the problem is.
For shows such as One Piece, it's because it the episodes are still being made and my logic doesn't consider for that. It should be an easy fix, but I'll only look at it next week. If I find time during the weekend, I'll definitely fix it.
Sorry, for the inconvenience.

**Comment by SageTendo** [comment]
Seems to be working on shows that are still running.
