### ISSUE TITLE
That Time I got Reincarnated as a Slime 3rd Season not showing

### ISSUE THREAD

**Issue by rajinstar** [SageTendo/mal-stremio-addon#22]
I face a problem that some anime are not showing in the stremio in the addons. I will give you a anime name: That Time I got Reincarnated as a Slime 3rd Season. Maybe some anime has a problem of loading like these. Can you fix this problem. It's an urgency. I am a anime fan. I love to watch anime. A
I mostly use Stremio. But this problem prevents me to watch anime. I will provide the Screen Recording from Stremio to explain the problem in a better way.

https://github.com/user-attachments/assets/057d3172-908b-4f0d-93b2-f7cc60cd6b20

**Comment by SageTendo** [comment]
Thanks for the video demo, I managed to reproduce the problem and see what was going on. The issue seems to be with the Kitsu addon, for some reason the MAL IDs for Season 1 and  Season 3 point to the same Kitsu ID. Sadly this is something I can't fix on my end. But I can reach out to the dev of that addon.

Sorry for the trouble.

**Comment by rajinstar** [comment]
Thanks. I also found another problem. Alya Sometimes Hides Her Feelings in Russian - this anime is also not showing and just showing other anime. Same problem like That Time I got Reincarnated as a Slime.

**Comment by rajinstar** [comment]
That time I got Reincarnated as a slime 3rd season not showing the problem is solved.

**Comment by SageTendo** [comment]
> Thanks a lot. @SageTendo, I also found another problem. **Alya Sometimes Hides Her Feelings in Russian**, this anime is also not showing and just showing other anime. Same problem like That Time I got Reincarnated as a Slime.

Another user had a similar issue:
https://github.com/SageTendo/mal-stremio-addon/issues/21#issuecomment-2322843298

The issue seems to  be related to the mapping of MAL to Kitsu IDs and Kitsu to MAL ID, but if you play it from the Kitsu list it syncs just fine.

**Comment by rajinstar** [comment]
@SageTendo, but I just want to track it to Mal Automatically while watching anime.
