### ISSUE TITLE
You update the addon to v2.0.3. But, I installed the addon that has v2.0.2. Why, I don't get the updated addon from the website!?

### ISSUE THREAD

**Issue by rajinstar** [SageTendo/mal-stremio-addon#23]
@SageTendo, You update the addon named **MAL-Stremio-Addon**. But, I don't get any update from the website where I connect my MAL account and install the addon in Stremio. Currently, my Stremio app MAL-Stremio-Addon's version is v2.0.2. But, you already updated the addon to v2.0.3. but why don't we get an updated addon from the website.

**Comment by SageTendo** [comment]
The update is a minor backend update, it is still compatible with older version.  I had forgotten to change the version in the manifest. I'll update the manifest so it reflects on your side when you reinstall the addon. 
Sorry about that.
