### ISSUE TITLE
[proposal] add support to show the other seasons for an entry

### ISSUE THREAD

**Issue by npateras** [SageTendo/mal-stremio-addon#25]
Use case:
1. Add Anime X season 2 to my MAL
2. Go to stremio and find it
3. Clicking on the season menu doesn't show you the rest of the seasons and it always show as "Season 1".

Proposal:
Add a way for that to be flexible.

**Comment by SageTendo** [comment]
I'm not sure I understand. Is the anime called "Anime X"? Episode information comes from the kitsu addon so that depends on what the kitsu addon returns. Some shows are returned as having one season, instead of being split.

**Comment by npateras** [comment]
> I'm not sure I understand. Is the anime called "Anime X"? Episode information comes from the kitsu addon so that depends on what the kitsu addon returns. Some shows are returned as having one season, instead of being split.

Anime X refers to an example, but I think my problem is because I was missing the Kitsu addon from my stremio, that's why I couldn't see the rest of the seasons. I will test it and let you know.

**Comment by npateras** [comment]
I confirm that this issue is persistent even with the [kitsu addon](https://anime-kitsu.strem.fun/manifest.json). Just to explain the issue again...
I have re:zero season 3 on my MAL list. However, it shows that we are on season 1 while we are on season 3... and I can't click on the dropdown to select the other seasons, it forces me to go and find them separately.

Disadvantages:
- Stremio won't notify me when there is a new season.
- I won't be able to see all the seasons of the same anime in the same entry.

![image](https://github.com/user-attachments/assets/668d7ebd-f45e-47a5-95f7-51a1994dfa8e)

**Comment by npateras** [comment]
> The issue here is that MyAnimeList and Kitsu's APIs return uncategorized episodes for some shows like One Piece, or Naruto (Usually long running shows). Other shows are handled differently, treating seasons as different entries in MAL/Kitsu's database, so that's why some shows; for example, "The Time I Got Re-incarnated as a Slime" have seasons being treated as different shows. Unfortunately, that is something I can't really handle properly for all shows, sorry.
> 
> If there's nothing else, can I close this issue?

I see, thank you.
