### ISSUE TITLE
Serverless function crashed

### ISSUE THREAD

**Issue by EdwinRodger** [SageTendo/mal-stremio-addon#31]
![Screenshot_20241222-234140.png](https://github.com/user-attachments/assets/bf5b51d9-a77c-45a7-9045-62205a37d32a)

As soon as I login to MAL and authorise the request, the vercel server crashes

**Comment by SageTendo** [comment]
Hi @EdwinRodger, looks to be working now. 
Some weird issue on MAL's callback configuration side.

Let me know if everything is working as intended.

**Comment by EdwinRodger** [comment]
Now it's working as intended! Also showing the list properly. Thanks! Happy Christmas!

**Comment by SageTendo** [comment]
Thanks for the feedback. Happy Christmas to you too :)
